In [1]:
import pandas as pd
import numpy as np

In [2]:
jeju = pd.read_csv('data/jeju_traffic.tsv',sep='\t')
jeju

,id,base_date,day_of_week,base_hour,lane_count,road_rating,road_name,multi_linked,connect_code,maximum_speed_limit,...,road_type,start_node_name,start_latitude,start_longitude,start_turn_restricted,end_node_name,end_latitude,end_longitude,end_turn_restricted,target
0,TRAIN_0000000,20220623,목,17,1,106,지방도1112호선,0,0,60.0,...,3,제3교래교,33.427747,126.662612,없음,제3교래교,33.427749,126.662335,없음,52.0
1,TRAIN_0000001,20220728,목,21,2,103,일반국도11호선,0,0,60.0,...,0,광양사거리,33.500730,126.529107,있음,KAL사거리,33.504811,126.526240,없음,30.0
2,TRAIN_0000002,20211010,일,7,2,103,일반국도16호선,0,0,80.0,...,0,창고천교,33.279145,126.368598,없음,상창육교,33.280072,126.362147,없음,61.0
3,TRAIN_0000003,20220311,금,13,2,107,태평로,0,0,50.0,...,0,남양리조트,33.246081,126.567204,없음,서현주택,33.245565,126.566228,없음,20.0
4,TRAIN_0000004,20211005,화,8,2,103,일반국도12호선,0,0,80.0,...,0,애월샷시,33.462214,126.326551,없음,애월입구,33.462677,126.330152,없음,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999994,TRAIN_0999994,20220214,월,11,1,106,지방도1112호선,0,0,60.0,...,0,송당입구,33.478605,126.783057,없음,덕천입구,33.494684,126.806104,없음,51.0
999995,TRAIN_0999995,20211019,화,16,2,107,중앙로,0,0,60.0,...,0,김약국,33.247607,126.561943,없음,한남투자,33.252712,126.561124,없음,16.0
999996,TRAIN_0999996,20211217,금,9,3,106,지방도1132호선,0,0,70.0,...,3,용흥교(동측),33.250624,126.489733,없음,강정교,33.250604,126.489259,없음,53.0
999997,TRAIN_0999997,20220118,화,4,2,103,일반국도16호선,0,0,80.0,...,0,상창교차로,33.280963,126.356788,없음,상창육교,33.280115,126.361832,없음,82.0
999998,TRAIN_0999998,20220303,목,11,1,107,-,0,0,60.0,...,3,서중2교,33.331742,126.676431,없음,서중2교,33.331981,126.677098,없음,61.0

In [4]:
jeju['datetime'] = jeju['base_date'].apply(lambda x: pd.to_datetime(str(x), format='%Y-%m-%d'))

In [5]:
jeju_2021 = jeju[(jeju['datetime']>='2021-09-01') & (jeju['datetime']<='2021-12-31')]

In [6]:
jeju_2021.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 393106 entries, 2 to 999996
Data columns (total 24 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   id                     393106 non-null  object
 1   base_date              393106 non-null  int64
 2   day_of_week            393106 non-null  object
 3   base_hour              393106 non-null  int64
 4   lane_count             393106 non-null  int64
 5   road_rating            393106 non-null  int64
 6   road_name              393106 non-null  object
 7   multi_linked           393106 non-null  int64
 8   connect_code           393106 non-null  int64
 9   maximum_speed_limit    393106 non-null  float64
 10  vehicle_restricted     393106 non-null  float64
 11  weight_restricted      393106 non-null  float64
 12  height_restricted      393106 non-null  float64
 13  road_type              393106 non-null  int64
 14  start_node_name        393106 non-null  object
 15  start_latitude         393106 non-null  float64
 16  start_longitude        393106 non-null  float64
 17  start_turn_restricted  393106 non-null  object
 18  end_node_name          393106 non-null  object
 19  end_latitude           393106 non-null  float64
 20  end_longitude          393106 non-null  float64
 21  end_turn_restricted    393106 non-null  object
 22  target                 393106 non-null  float64
 23  datetime               393106 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(9), int64(7), object(7)
memory usage: 75.0+ MB

In [7]:
jeju_2021.columns

Index(['id', 'base_date', 'day_of_week', 'base_hour', 'lane_count',
       'road_rating', 'road_name', 'multi_linked', 'connect_code',
       'maximum_speed_limit', 'vehicle_restricted', 'weight_restricted',
       'height_restricted', 'road_type', 'start_node_name', 'start_latitude',
       'start_longitude', 'start_turn_restricted', 'end_node_name',
       'end_latitude', 'end_longitude', 'end_turn_restricted', 'target',
       'datetime'],
      dtype='object')

In [8]:
jeju_2021_sp = jeju_2021[['datetime', 'day_of_week','base_hour','lane_count',
                         'road_rating', 'road_name', 'start_node_name','start_latitude',
                         'start_longitude','end_node_name', 'end_latitude','end_longitude']].reset_index(drop=True)

In [9]:
car_accident = pd.read_csv('data/도로교통공단_사망 교통사고 정보_20211231.csv', encoding = 'euc_kr')

In [10]:
car_accident

,발생년,발생년월일시,주야,요일,사망자수,부상자수,중상자수,경상자수,부상신고자수,발생지시도,...,사고유형,가해자법규위반,도로형태_대분류,도로형태,가해자_당사자종별,피해자_당사자종별,발생위치X(UTMK),발생위치Y(UTMK),경도,위도
0,2021,2021-01-01 03:00,야,금,1,3,0,3,0,경북,...,추돌,안전운전 의무 불이행,교차로,교차로부근,승용차,승용차,1097010.0,1793385.0,128.578152,36.132653
1,2021,2021-01-01 09:00,주,금,1,0,0,0,0,충남,...,공작물충돌,안전운전 의무 불이행,단일로,기타단일로,승용차,없음,902369.0,1847109.0,126.408201,36.616845
2,2021,2021-01-01 15:00,주,금,1,0,0,0,0,강원,...,측면충돌,안전운전 의무 불이행,교차로,교차로내,원동기장치자전거,승용차,1123975.0,1974509.0,128.907484,37.761842
3,2021,2021-01-01 19:00,야,금,1,0,0,0,0,전남,...,횡단중,안전운전 의무 불이행,단일로,기타단일로,화물차,보행자,886507.0,1613961.0,126.263573,34.513391
4,2021,2021-01-01 21:00,야,금,1,0,0,0,0,경기,...,기타,기타,단일로,기타단일로,승용차,보행자,953522.0,1915403.0,126.976011,37.236327
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2811,2021,2021-12-31 16:00,주,금,1,0,0,0,0,경북,...,정면충돌,안전운전 의무 불이행,교차로,교차로내,승용차,이륜차,1119020.0,1766895.0,128.818730,35.891434
2812,2021,2021-12-31 17:00,주,금,1,0,0,0,0,제주,...,추돌,안전운전 의무 불이행,단일로,기타단일로,화물차,화물차,940588.0,1503049.6,126.860248,33.517699
2813,2021,2021-12-31 18:00,야,금,1,0,0,0,0,강원,...,횡단중,보행자 보호의무 위반,단일로,기타단일로,승용차,보행자,1023127.0,1982332.0,127.762845,37.840465
2814,2021,2021-12-31 19:00,야,금,1,0,0,0,0,경북,...,횡단중,보행자 보호의무 위반,교차로,교차로횡단보도내,승용차,보행자,1058805.0,1824755.0,128.155943,36.418521
2815,2021,2021-12-31 21:00,야,금,1,0,0,0,0,강원,...,전복,중앙선 침범,단일로,기타단일로,승용차,없음,1042559.0,2010975.0,127.985386,38.097913

In [11]:
car = car_accident.query("발생지시도 == '제주'")

In [12]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48 entries, 23 to 2812
Data columns (total 23 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   발생년          48 non-null     int64
 1   발생년월일시       48 non-null     object
 2   주야           48 non-null     object
 3   요일           48 non-null     object
 4   사망자수         48 non-null     int64
 5   부상자수         48 non-null     int64
 6   중상자수         48 non-null     int64
 7   경상자수         48 non-null     int64
 8   부상신고자수       48 non-null     int64
 9   발생지시도        48 non-null     object
 10  발생지시군구       48 non-null     object
 11  사고유형_대분류     48 non-null     object
 12  사고유형_중분류     48 non-null     object
 13  사고유형         48 non-null     object
 14  가해자법규위반      48 non-null     object
 15  도로형태_대분류     48 non-null     object
 16  도로형태         48 non-null     object
 17  가해자_당사자종별    48 non-null     object
 18  피해자_당사자종별    48 non-null     object
 19  발생위치X(UTMK)  48 non-null     float64
 20  발생위치Y(UTMK)  48 non-null     float64
 21  경도           48 non-null     float64
 22  위도           48 non-null     float64
dtypes: float64(4), int64(6), object(13)
memory usage: 9.0+ KB

In [13]:
car['발생년월일시'] = pd.to_datetime(car['발생년월일시'])

/var/folders/p7/570vhrqx0qs082gkv7y5wy780000gn/T/ipykernel_8600/1132470394.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['발생년월일시'] = pd.to_datetime(car['발생년월일시'])

In [14]:
car['datetime'] = car['발생년월일시'].dt.date
car['hour'] = car['발생년월일시'].dt.hour

/var/folders/p7/570vhrqx0qs082gkv7y5wy780000gn/T/ipykernel_8600/3152136194.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['datetime'] = car['발생년월일시'].dt.date
/var/folders/p7/570vhrqx0qs082gkv7y5wy780000gn/T/ipykernel_8600/3152136194.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['hour'] = car['발생년월일시'].dt.hour

In [15]:
car.columns

Index(['발생년', '발생년월일시', '주야', '요일', '사망자수', '부상자수', '중상자수', '경상자수', '부상신고자수',
       '발생지시도', '발생지시군구', '사고유형_대분류', '사고유형_중분류', '사고유형', '가해자법규위반',
       '도로형태_대분류', '도로형태', '가해자_당사자종별', '피해자_당사자종별', '발생위치X(UTMK)',
       '발생위치Y(UTMK)', '경도', '위도', 'datetime', 'hour'],
      dtype='object')

In [16]:
car_sp = car[['datetime','주야','요일','hour','사망자수','부상자수','중상자수','경상자수',
             '부상신고자수','발생지시도','발생지시군구','사고유형','경도','위도']]

In [17]:
jeju_start = jeju_2021_sp[['datetime','day_of_week','base_hour','road_name',
                  'start_node_name','start_latitude','start_longitude']].reset_index(drop=True)
jeju_end =  jeju_2021_sp[['datetime','day_of_week','base_hour','road_name',
                  'end_node_name','end_latitude','end_longitude']].reset_index(drop=True)

In [18]:
jeju_start = jeju_start.dropna()
jeju_end = jeju_end.dropna()

In [19]:
# jeju_start.info()
jeju_start

,datetime,day_of_week,base_hour,road_name,start_node_name,start_latitude,start_longitude
0,2021-10-10,일,7,일반국도16호선,창고천교,33.279145,126.368598
1,2021-10-05,화,8,일반국도12호선,애월샷시,33.462214,126.326551
2,2021-09-13,월,7,경찰로,시청입구2,33.249949,126.505664
3,2021-12-13,월,16,외도천교,외도천교,33.482392,126.441622
4,2021-10-04,월,15,경찰로,신성교회,33.253074,126.506393
...,...,...,...,...,...,...,...
393101,2021-12-12,일,20,일반국도16호선,제2가시교,33.364471,126.769568
393102,2021-09-22,수,8,동홍로,오렌지빌라B동,33.258653,126.568490
393103,2021-09-22,수,8,일반국도95호선,전표1교,33.320921,126.350630
393104,2021-10-19,화,16,중앙로,김약국,33.247607,126.561943
393105,2021-12-17,금,9,지방도1132호선,용흥교(동측),33.250624,126.489733

In [20]:
car_sp = car_sp[['datetime','주야','요일','hour','사망자수','부상자수','중상자수',
                 '경상자수','부상신고자수','사고유형','경도','위도']]

In [21]:
car_sp['datetime'] = pd.to_datetime(car_sp['datetime'])

In [22]:
car_sp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48 entries, 23 to 2812
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  48 non-null     datetime64[ns]
 1   주야        48 non-null     object
 2   요일        48 non-null     object
 3   hour      48 non-null     int64
 4   사망자수      48 non-null     int64
 5   부상자수      48 non-null     int64
 6   중상자수      48 non-null     int64
 7   경상자수      48 non-null     int64
 8   부상신고자수    48 non-null     int64
 9   사고유형      48 non-null     object
 10  경도        48 non-null     float64
 11  위도        48 non-null     float64
dtypes: datetime64[ns](1), float64(2), int64(6), object(3)
memory usage: 4.9+ KB

In [ ]:
jeju_start['start_latitude_2'] = jeju_start['start_latitude'].round(2)
jeju_start['start_longtitude_2'] = jeju_start['start_longtitude'].round(2)